Feature: Helpers
	Scenarios in this feature are not for testing -- they are mainly used in order to generate some User Stories for human testers to work with

Scenario: Create very complex user story
	Given I started to create a new User Story with the name 'Mega-complex Story'
	And I added a new Rule that says 'Do not start a new project on Fridays'
	And I added a new Rule that says 'Add the ingredients when the water starts to boil'
	And I added a new Rule that says 'When camping in the jungle, drink a glass of water every two hours'
	And I added a new Rule that says 'Never went camping near water bodies during the rains'
	And I added a new Rule that says 'When serving food, two handfuls make a portion'
	And I illustrated the Rule 'Do not start a new project on Fridays' with the example 'Mary did that last year and she was fired the next month.'
	And I illustrated the Rule 'Do not start a new project on Fridays' with the example 'I have several divs that seem to over lap as per the fiddle but want the homemidcontent div to be below the homebanner div'
	And I illustrated the Rule 'Do not start a new project on Fridays' with the example 'That is unnecessary,it happened because he didn't cleared the above floated elements.He will eventually run into problems if he don't clear the floats and keep using margins'
	And I illustrated the Rule 'Do not start a new project on Fridays' with the example 'Not in lone splendour hung aloft the night'
	And I illustrated the Rule 'Add the ingredients when the water starts to boil' with the example 'The moving waters at their priestlike task'
	And I illustrated the Rule 'Add the ingredients when the water starts to boil' with the example 'Gazing on the new soft-fallen mask'
	And I illustrated the Rule 'Add the ingredients when the water starts to boil' with the example 'No--yet still stedfast, still unchangeable'
	And I illustrated the Rule 'Add the ingredients when the water starts to boil' with the example 'To feel for ever its soft fall and swell'
	And I illustrated the Rule 'Add the ingredients when the water starts to boil' with the example 'Awake for ever in a sweet unrest'
	And I illustrated the Rule 'Add the ingredients when the water starts to boil' with the example 'And so live ever--or else swoon to death'
	And I illustrated the Rule 'When camping in the jungle, drink a glass of water every two hours' with the example 'He did not wear his scarlet coat'
	And I illustrated the Rule 'When camping in the jungle, drink a glass of water every two hours' with the example 'For blood and wine are red'
	And I illustrated the Rule 'When camping in the jungle, drink a glass of water every two hours' with the example 'And blood and wine were on his hands'
	And I illustrated the Rule 'Never went camping near water bodies during the rains' with the example 'When they found him with the dead'
	And I illustrated the Rule 'Never went camping near water bodies during the rains' with the example 'The poor dead woman whom he loved'
	And I illustrated the Rule 'Never went camping near water bodies during the rains' with the example 'And murdered in her bed'
	And I illustrated the Rule 'Never went camping near water bodies during the rains' with the example 'He walked amongst the Trial Men'
	And I illustrated the Rule 'When serving food, two handfuls make a portion' with the example 'In a suit of shabby grey'
	And I illustrated the Rule 'When serving food, two handfuls make a portion' with the example 'A cricket cap was on his head'
	And I illustrated the Rule 'When serving food, two handfuls make a portion' with the example 'And his step seemed light and ga'
	And I illustrated the Rule 'When serving food, two handfuls make a portion' with the example 'But I never saw a man who looked'
	And I illustrated the Rule 'When serving food, two handfuls make a portion' with the example 'So wistfully at the day'
	And I illustrated the Rule 'When serving food, two handfuls make a portion' with the example 'I never saw a man who looked'
	And I added a new Question that says 'But who would stand in hempen band Upon a scaffold high, And through a murderer’s collar take His last look at the sky?'
	And I added a new Question that says 'And what should Human Pity do Pent up in Murderers’ Hole?'
	And I added a new Question that says 'What word of grace in such a place Could help a brother’s soul?'
	When I complete editing the User Story 
